// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc2
// source: gossip.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeHealth int32

const (
	NodeHealth_ALIVE   NodeHealth = 0
	NodeHealth_SUSPECT NodeHealth = 1
	NodeHealth_DEAD    NodeHealth = 2
)

// Enum value maps for NodeHealth.
var (
	NodeHealth_name = map[int32]string{
		0: "ALIVE",
		1: "SUSPECT",
		2: "DEAD",
	}
	NodeHealth_value = map[string]int32{
		"ALIVE":   0,
		"SUSPECT": 1,
		"DEAD":    2,
	}
)

func (x NodeHealth) Enum() *NodeHealth {
	p := new(NodeHealth)
	*p = x
	return p
}

func (x NodeHealth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeHealth) Descriptor() protoreflect.EnumDescriptor {
	return file_gossip_proto_enumTypes[0].Descriptor()
}

func (NodeHealth) Type() protoreflect.EnumType {
	return &file_gossip_proto_enumTypes[0]
}

func (x NodeHealth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeHealth.Descriptor instead.
func (NodeHealth) EnumDescriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_INTER_GOSSIP MessageType = 0
	MessageType_INTRA_GOSSIP MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "INTER_GOSSIP",
		1: "INTRA_GOSSIP",
	}
	MessageType_value = map[string]int32{
		"INTER_GOSSIP": 0,
		"INTRA_GOSSIP": 1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_gossip_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_gossip_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{1}
}

type NodeState struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Group  string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Health NodeHealth             `protobuf:"varint,3,opt,name=health,proto3,enum=main.NodeHealth" json:"health,omitempty"`
	// unix nano timestamp
	LastSeen       int64  `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	SuspicionCount int32  `protobuf:"varint,5,opt,name=suspicion_count,json=suspicionCount,proto3" json:"suspicion_count,omitempty"`
	Version        uint64 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeState) Reset() {
	*x = NodeState{}
	mi := &file_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeState) ProtoMessage() {}

func (x *NodeState) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeState.ProtoReflect.Descriptor instead.
func (*NodeState) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *NodeState) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeState) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *NodeState) GetHealth() NodeHealth {
	if x != nil {
		return x.Health
	}
	return NodeHealth_ALIVE
}

func (x *NodeState) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *NodeState) GetSuspicionCount() int32 {
	if x != nil {
		return x.SuspicionCount
	}
	return 0
}

func (x *NodeState) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GossipMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   MessageType            `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=main.MessageType" json:"message_type,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	States        []*NodeState           `protobuf:"bytes,3,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *GossipMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_INTER_GOSSIP
}

func (x *GossipMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *GossipMessage) GetStates() []*NodeState {
	if x != nil {
		return x.States
	}
	return nil
}

var File_gossip_proto protoreflect.FileDescriptor

const file_gossip_proto_rawDesc = "" +
	"\n" +
	"\fgossip.proto\x12\x04main\"\xc4\x01\n" +
	"\tNodeState\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12(\n" +
	"\x06health\x18\x03 \x01(\x0e2\x10.main.NodeHealthR\x06health\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x03R\blastSeen\x12'\n" +
	"\x0fsuspicion_count\x18\x05 \x01(\x05R\x0esuspicionCount\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x04R\aversion\"\x8b\x01\n" +
	"\rGossipMessage\x124\n" +
	"\fmessage_type\x18\x01 \x01(\x0e2\x11.main.MessageTypeR\vmessageType\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12'\n" +
	"\x06states\x18\x03 \x03(\v2\x0f.main.NodeStateR\x06states*.\n" +
	"\n" +
	"NodeHealth\x12\t\n" +
	"\x05ALIVE\x10\x00\x12\v\n" +
	"\aSUSPECT\x10\x01\x12\b\n" +
	"\x04DEAD\x10\x02*1\n" +
	"\vMessageType\x12\x10\n" +
	"\fINTER_GOSSIP\x10\x00\x12\x10\n" +
	"\fINTRA_GOSSIP\x10\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_gossip_proto_rawDescOnce sync.Once
	file_gossip_proto_rawDescData []byte
)

func file_gossip_proto_rawDescGZIP() []byte {
	file_gossip_proto_rawDescOnce.Do(func() {
		file_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gossip_proto_rawDesc), len(file_gossip_proto_rawDesc)))
	})
	return file_gossip_proto_rawDescData
}

var file_gossip_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gossip_proto_goTypes = []any{
	(NodeHealth)(0),       // 0: main.NodeHealth
	(MessageType)(0),      // 1: main.MessageType
	(*NodeState)(nil),     // 2: main.NodeState
	(*GossipMessage)(nil), // 3: main.GossipMessage
}
var file_gossip_proto_depIdxs = []int32{
	0, // 0: main.NodeState.health:type_name -> main.NodeHealth
	1, // 1: main.GossipMessage.message_type:type_name -> main.MessageType
	2, // 2: main.GossipMessage.states:type_name -> main.NodeState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gossip_proto_init() }
func file_gossip_proto_init() {
	if File_gossip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gossip_proto_rawDesc), len(file_gossip_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gossip_proto_goTypes,
		DependencyIndexes: file_gossip_proto_depIdxs,
		EnumInfos:         file_gossip_proto_enumTypes,
		MessageInfos:      file_gossip_proto_msgTypes,
	}.Build()
	File_gossip_proto = out.File
	file_gossip_proto_goTypes = nil
	file_gossip_proto_depIdxs = nil
}
